In [1]:
import torch
import torchax

torchax.enable_globally()

/usr/local/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:354: UserWarning: Device capability of jax unspecified, assuming `cpu` and `cuda`. Please specify it via the `devices` argument of `register_backend`.
  warnings.warn(


In [2]:
# Here's a CPU tensor
a = torch.randn(2, 3, device='cpu')
a

tensor([[ 1.0236,  0.3781, -2.6286],
        [ 0.5083, -1.0613,  1.4135]])

In [3]:
# Here's a JAX tensor
b = torch.randn(2, 3, device='jax')
b

Tensor(<class 'jaxlib.xla_extension.ArrayImpl'> [[ 1.4053154  -1.8948289  -0.28394678]
 [ 0.24931182  0.9149442   0.21975662]])

In [4]:
# Move CPU tensor to JAX
a.to('jax')

Tensor(<class 'jaxlib.xla_extension.ArrayImpl'> [[ 1.0235875   0.37808326 -2.6286266 ]
 [ 0.5082623  -1.0612806   1.4135425 ]])

In [5]:
# Move JAX tensor to CPU
b.to('cpu')

/usr/local/lib/python3.10/site-packages/torchax/ops/mappings.py:46: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /workspaces/torch/pytorch/torch/csrc/utils/tensor_numpy.cpp:203.)
  res = torch.from_numpy(numpy.asarray(x))


tensor([[ 1.4053, -1.8948, -0.2839],
        [ 0.2493,  0.9149,  0.2198]])

In [6]:
# We can also set the default device to JAX.
torch.set_default_device('jax')

In [ ]:
# Then all tensors will be created on JAX by default.
# But this fails likely due to a bug.
torch.randn(2, 3)

RuntimeError: PyTorch is not linked with support for jax devices