In [1]:
import torch
import torchax

torchax.enable_globally()

/usr/local/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:354: UserWarning: Device capability of jax unspecified, assuming `cpu` and `cuda`. Please specify it via the `devices` argument of `register_backend`.
  warnings.warn(


In [3]:
# Here's a CPU tensor
a = torch.randn(2, 3, device='cpu')
a

tensor([[-0.8775,  1.1114,  1.6120],
        [-0.0937,  1.2410,  0.6565]])

In [4]:
# Here's a JAX tensor
b = torch.randn(2, 3, device='jax')
b

Tensor(<class 'jaxlib.xla_extension.ArrayImpl'> [[-1.160794    0.30849636  1.3150151 ]
 [-1.4054272  -1.1027737  -0.34123442]])

In [5]:
# Move CPU tensor to JAX
a.to('jax')

Tensor(<class 'jaxlib.xla_extension.ArrayImpl'> [[-0.8774722   1.1114085   1.611951  ]
 [-0.09367315  1.2410246   0.6564752 ]])

In [6]:
# Move JAX tensor to CPU
b.to('cpu')

/usr/local/lib/python3.10/site-packages/torchax/ops/mappings.py:46: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /workspaces/torch/pytorch/torch/csrc/utils/tensor_numpy.cpp:203.)
  res = torch.from_numpy(numpy.asarray(x))


tensor([[-1.1608,  0.3085,  1.3150],
        [-1.4054, -1.1028, -0.3412]])